name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download BlazeFace
      uses: actions/checkout@v3
      with:
        repository: 'hollance/BlazeFace-PyTorch'
        path: 'model/bazeface'
        
    - name: Build the Docker image
      run: docker build . --file build/Dockerfile --tag the-smile:$(date +%Y%m%d-%s)  --tag the-smile:latest

    - name: Check BlazeFace
      run: ls -la model/blazeface
